version: '3'

services:
    db:
        image: postgres:15.3
        restart: always
        ports:
            - '5433:5432'
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
        container_name: anylistDB
        expose:
            - '5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
